[program:pos-scheduler]
process_name=%(program_name)s
directory=/var/www/pos/current
command=php artisan schedule:work
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/pos/current/storage/logs/supervisor-scheduler.log
stopwaitsecs=60